---
title: "Plotting examples"
author: "Vilmantas Gėgžna"
date: "`r Sys.Date()`"
output:
    rmarkdown::html_vignette: 
        toc: yes
        number_sections: yes

vignette: >
  %\VignetteIndexEntry{Plotting examples}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteDepends{plotly}
  %\VignetteEncoding{UTF-8}
---
```{r options, echo = FALSE, message = FALSE, warning = FALSE}
optDEF <- knitr::opts_chunk$get()
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")



knitr::opts_chunk$set(fig.width = 5, fig.align = 'center')

```

Load packages
==============
```{r Load packages, message = FALSE, warning = FALSE}
library(spHelper)

```


Some Examples
==============


```{r, fig.align='center',fig.width= 5, fig.cap = c("**Fig1.** Spectra of Components (_hyperSpec_ package)", "**Fig2.** Spectra of Components (_spHelper_ package)","**Fig3.** Spectra of Components (_spHelper_ and _plotly_ packages)", "**Fig4.** Amplitudes by groups (_spHelper_ package)")}
data("Loadings")
data("Scores")

qplotspc(Loadings) 

plot_kSpFacets(Loadings)

plot_kSpFacets(Loadings) %>% ggplotly()

plot_kAmp(Scores)

```



```{r,fig.width= 5, fig.cap = "**Fig2.** 'Plotly' example."}

dsamp <- diamonds[sample(nrow(diamonds), 1000), ]
qplot(carat, price, data = dsamp, colour = clarity) %>% ggplotly()

```

plot_kSpFacets
================
```{r plot_kSpFacets}
library(hyperSpec)
plot_kSpFacets(flu, Title = "Flu dataset")
plot_kSpFacets(flu, Title = "Flu dataset", normalize = 1)
plot_kSpFacets(flu, Title = "Flu dataset", normalize = FALSE)
plot_kSpFacets(flu, Title = "Flu dataset", normalize = -1)

```

Remove fill
------------
```{r}
flu$c2 <- as.factor(flu$c)
plot_kSp(flu, Title = "Flu dataset", names = 'c2', filled = F)
```

Name of the legend
------------------
```{r}
plot_kSp(flu, Title = "Flu dataset", names = 'c2', legendName = FALSE)
plot_kSp(flu, Title = "Flu dataset", names = 'c2', legendName = TRUE)
plot_kSp(flu, Title = "Flu dataset", names = 'c2', legendName = "Concentration")
```

uniPeak
=======
```{r}
 #  Example 1 ----------------------------------------------------------------------

 x     <- seq(-10,20,.1)
 y0    <- GaussAmp(x, c = 0, A = 1) + GaussAmp(x, c = 10, A = 2) - .5
 y0NEW <- uniPeak(y0)

 # Plot the results
 par(mfrow = c(1,1))
 plot( x, y0,    type = "l", lty = 3,
         main = "'uniPeak' keeps positive part \n of highest peak only" );
 lines(x, y0NEW, type = "l", lty = 1, lwd = 3);
 legend("topleft", legend = c("Before","After"), lty = c(3,1))

```
```{r, fig.height=10}
 #  Example 2 ----------------------------------------------------------------------

 x  = seq(-10,20,.1)
 y1 = (sin(x/4) + GaussAmp(x))
 y2 = (2*sin(x) + sin(x/5) + GaussAmp(x, c = 5))
 y  = rbind(y1,y2)

 yNEW <- apply(y,1,uniPeak)

 par(mfrow = c(3,1))

 # plot 1
 matplot(x, t(y), type = "l", lty = 3,
         main = "A - Initial curves");
 abline(h = 0)

 # plot 2
 matplot(x,yNEW, type = "l", lty = 1,lwd = 3,
         main = "B - Only the highest positive\n peaks per curve");
 abline(h = 0)

 # plot 3: both plots together
 matplot(x, t(y), type = "l", lty = 3, main = "A and B together");
 matlines(x,yNEW, type = "l", lty = 1,lwd = 3);
 abline(h = 0)
 
 par(mfrow = c(1,1))
```

subt
======
```{r}
 subt("Cars")
 ## bold("Cars")

 subt("Cars","Distance vs. speed")
 ## atop(bold("Cars"), atop(italic("Distance vs. speed")))

 # ----------------------------------------------------------------

 plot(cars[,1:2], main = "Cars")
 plot(cars[,1:2], main = subt("Cars")) # the same as in previous line
 plot(cars[,1:2], main = subt("Cars","Distance vs. speed"))
 plot(cars[,1:2], main = subt(subTitle = "Distance vs. speed"))

 # ----------------------------------------------------------------

 library(ggplot2)

 g <- qplot(mpg, wt, data = mtcars)
 g + ggtitle("Cars") # non-bold title
 g + ggtitle(subt("Cars")) # bold title
 g + ggtitle(subt("Cars","Distance vs. speed"))
 g + ggtitle(subt(subTitle = "Distance vs. speed"))


 # ----------------------------------------------------------------

 library(lattice)

 xyplot(eruptions~waiting, data = faithful)

 xyplot(eruptions~waiting, data = faithful,
  main = "Old Faithful Geyser Data")

 xyplot(eruptions~waiting, data = faithful,
  main = subt("Old Faithful Geyser Data"))

 xyplot(eruptions~waiting, data = faithful,
  main = subt("Old Faithful Geyser", "Data"))

 xyplot(eruptions~waiting, data = faithful,
  main = subt(subTitle = "Old Faithful Geyser Data"))
```

qplotStat
=========

```{r}
 qplotStat(chondro,clusters,mean)
 qplotStat(chondro,clusters,mean,All = FALSE)
 qplotStat(chondro,clusters,mean_sd,All = FALSE) + facet_grid(.~clusters)

 qplotStat(chondro,clusters,median,All = FALSE, fixed.colors = FALSE)
 qplotStat(chondro,clusters,median, "My Title")


 # Use `.aggregate` in making facets, to avoid facet called "NA":

 qplotStat(chondro,clusters,mean_pm_sd) + facet_grid(.~clusters)
 qplotStat(chondro,clusters,mean_pm_sd) + facet_grid(.~.aggregate)
```

The other dataset

```{r}
 qplotStat(Spectra,gr,mean)
 qplotStat(Spectra,gr,mean,All = FALSE)
 qplotStat(Spectra,gr,mean_sd,All = FALSE) + facet_grid(.~gr)

 qplotStat(Spectra,gr,median,All = FALSE, fixed.colors = FALSE)
 qplotStat(Spectra,gr,median, "My Title")


 # Use `.aggregate` in making facets, to avoid facet called "NA":

 qplotStat(Spectra,gr,mean_pm_sd) + facet_grid(.~gr)
 qplotStat(Spectra,gr,mean_pm_sd) + facet_grid(.~.aggregate)
```

PlotConfusion
=============


```{r, echo=FALSE}
knitr::opts_chunk$set(optDEF)
knitr::opts_chunk$set(fig.show = "hold")
```

```{r}
set.seed(165)

N <- 1000 # number of observations

Prediction <- sample(c("A","B","C","D"),N, replace = TRUE)
Reference  <- sample(c("A", "B","C","D"),N, replace = TRUE)

# Random guess  =====================
conf <- table(Prediction,Reference)

PlotConfusion(conf, subTitle = "Correct by chance")

# At least 40% of the cases agree =====================
ind2 <- sample(1:N,round(0.5*N))
Reference[ind2] <- Prediction[ind2]
conf2 <- table(Prediction,Reference)

PlotConfusion(conf2, subTitle = "Correct >50%")

# Most of the cases agree =============================
ind3 <- sample(1:N,round(N*.8))
Reference[ind3] <- Prediction[ind3]
conf3 <- table(Prediction,Reference)

PlotConfusion(conf3, subTitle = "Correct >80%")
```

```{r}
# Proportions =========================================

PlotConfusion(conf3              , subTitle = "Counts")
PlotConfusion(prop.table(conf3),   subTitle = "Proportions (total sum = 1)")
PlotConfusion(prop.table(conf3,1), subTitle = "Proportions (row sums = 1)")
PlotConfusion(prop.table(conf3,2), subTitle = "Proportions (column sums = 1)")
```

```{r}
# Shades: proportional ================================

PlotConfusion(conf,shades = "prop",  subTitle = "Shades: 'prop', Correct by chance");
PlotConfusion(conf,shades = "max",   subTitle = "Shades: 'max', Correct by chance")

PlotConfusion(conf2,shades = "prop", subTitle = "Shades: 'prop', Correct >50%");
PlotConfusion(conf2,shades = "max",  subTitle = "Shades: 'max', Correct >50%")

PlotConfusion(conf3,shades = "prop", subTitle = "Shades: 'prop', Correct >80%");
PlotConfusion(conf3,shades = "max",  subTitle = "Shades: 'max', Correct >80%")
```

```{r}
# Shades: constant and none ===========================

PlotConfusion(conf3,shades = "const",subTitle = "Shades: constant"); PlotConfusion(conf3,shades = "none", subTitle = "Shades: none")

```

```{r}
n <- round(N/6)
Prediction[sample(which(Prediction == "A"),n,replace = TRUE)] <- sample(c("B","C"), n,replace = TRUE)
conf4 <- table(Prediction,Reference)

PlotConfusion(conf4, subTitle = "Imbalanced class proportions")

```



