#' [!] Plot the result of \code{\link{infoDim}} (ggplot2)
#'
#' Plot the result generated by function \code{\link{infoDim}}.
#'
#' @param Object Either an object (a list), generated by function
#'        \code{\link{infoDim}} or a matrix (to be passed to \code{infoDim}).
#'
#' @param n.comp.SHOW A number of components to show on x axis, default is 20.
#' This number is corrected if (a) vector of eigenvalues is smaller than 20
#' or (b) information dimension is higher than 15.
#'
#' @param selected (optional parameter) A number of components sellected
#'        (will be plotted as a separate vertical line).
#'
#' @param Title The title of the plot.
#' @param y.log Logical. If \code{TRUE} (default) the scale of  y axis is
#'       logarythmic.
#'
#' @param show.legend Logical. If \code{TRUE} (default) the legend is displayed.
#' @param ggtheme A function of ggplot2 theme to apply (e.g.: \link[ggplot2]{ggtheme}).
#'  Default is \code{theme_bw()}.
#'
#' @return A scree plot : plot which helps to
#'         determine the number of nenessary components (e.g. for PCA).\cr
#'         (A "ggplot" object.)
#'
#' @export
#'
#' @examples
#'  infoDim(Spectra)
#'
#' # ------------------------------------------------------
#'  my_matrix <- matrix(rexp(200, rate=.1), ncol=20)
#'  my_result <- infoDim(my_matrix)
#'
#'  # Investigate the result
#'  str(my_result)
#'  my_result$exactDim
#'  my_result$dim
#'
#'  #Plot
#'  my_plot <- plot_infoDim(my_result)
#'  my_plot
#'
#' @note http://www.originlab.com/doc%5Cen/Tutorial/images/Principal_Component_Analysis/Pca_scree_plot.png
#'
#' @family spHelper plots
#' @family information dimension functions

plot_infoDim <- function(Object, n.comp.SHOW = 20, selected = NA,
                         Title = "Scree Plot", y.log = TRUE,
                         show.legend = TRUE,
                         ggtheme = theme_bw()){

    if (!any(class(Object) == "infoDim"))    Object <- infoDim(Object)


    # Adjust n.comp.SHOW
    At_least         <- max(n.comp.SHOW,  Object$dim + 5)
    But_no_more_than <- length(Object$eigenval)
    n.comp.SHOW = min(At_least, But_no_more_than)
    ind <- 1:n.comp.SHOW

    # Prepare data ------------------------------------------------------------
    data <- with(Object,
                 data.frame(x         = n.comp[ind],
                            explained = 100 * explained[ind])
    )

    # Prepare annotations -----------------------------------------------------
    getTicks <- function(n = 10){
        function(x) {
            xMin <- min(x, na.rm = TRUE) #signif(min(x, na.rm = TRUE),1)
            xMax <- max(x, na.rm = TRUE)
            axisTicks(log10(c(xMin,xMax)), log = TRUE, nint = n)
        }
    }

    yMin <- signif(.75*min(data$explained), 1)

    annotations <- data.frame(
            Dim    = Object$exactDim,
            DimText = sprintf("Information dimension = %.1f",Object$exactDim),
            selected    = selected,
            selectedText = sprintf("# components selected = %d",selected)
    )

    # Create a plot ===========================================================

    p <- ggplot(data, aes(x, explained))
    p <- p + ggtheme # Add theme
    p <- p +
        geom_line(color = "#0080ff") +
        geom_point(color = "#0080ff", size = 3) +

        labs(x = "Number of components",
             y = "Explained variance, %",
             title = Title)

    # Add annotation lines
    p <- p + geom_vline(data = annotations,
                   linetype = "dashed",
                   aes(xintercept = Dim,
                       color = DimText),
                   show.legend = show.legend)

    if (!is.na(selected)) {
        p <- p + geom_vline(data = annotations,
                       linetype = "dashed",
                       aes(xintercept = selected,
                           color = selectedText),
                       show.legend = show.legend)
    }

    p <- p +
        scale_colour_manual(values = c("red3", "green3")) +
        theme(legend.title  = element_blank(),
              legend.position   = c(0.8, 0.8))
              # legend.background = element_rect(size = 0.5,
              #                                  linetype = "solid",
              #                                   colour  = "gray60")

    # Use log y scale --------------------------------------------------------

        if (y.log) {
            p <- p +
                scale_y_log10(breaks = getTicks(),
                              labels = prettyNum,
                              limits = c(yMin, NA)) +
                    annotation_logticks(sides = 'rl', color = "grey50") +
                    theme(panel.grid.minor = element_blank())
             }
   #  ------------------------------------------------------------------------
    return(p)
}


