#' @name plot_stat
#' @aliases plot_stat
#' @aliases qplotStat
#'
#' @title [+] Plot a summary statistic of spectroscopic data by group
#'
#' @description Plot a summary of spectroscopic data in hyperSpec object by group.
#' The summary statistic internally is generated by either function
#' \code{\link{spStat}} or \code{\link[hyperSpec]{aggregate}}.
#'
#' @template sp
#' @param by A grouping variable (either a vertor or a variaable name in \code{sp}).
#' @param FUN A function that calculates one or several summary statistics.
#' @param Title The main title of the plot.
#' @template subtitle
#' @param All Logical. If \code{TRUE}, plot additional corve for a statistic
#'                    of all spectra (\code{.ALL}), not devided to grroups.
#' @param fixed.colors - Logical. If \code{TRUE}, color scheme where \code{.ALL}
#'       is plotted as a black line is be used.
#' @param All.color A line color for \code{.ALL}.
#' @param gr.color Line colors (a vector) for each level in \code{by}.
#' @param All.linetype A line type for \code{.ALL}.
#' @param gr.linetype Line types (a vector) for each level in \code{by}.
#' @param All.size A line width for \code{.ALL}.
#' @param gr.size Line widths (a vector) for each level in \code{by}.
#' @param legend.title A title for legend. Default is no title.
#'
#'
#' @template ggplot
#' @export
#'
#' @examples
#'
#'
#' plot_stat(chondro,clusters,mean)
#' plot_stat(chondro,clusters,mean,All=FALSE)
#' plot_stat(chondro,clusters,mean_sd,All=FALSE) + facet_grid(.~clusters)
#'
#' plot_stat(chondro,clusters,median,All=FALSE, fixed.colors=FALSE)
#' plot_stat(chondro,clusters,median, "My Title")
#'
#'
#' # Make facets:
#'
#' plot_stat(chondro,clusters,mean_pm_sd) + facet_grid(.~clusters) + nTick_x(2)
#'
#' @seealso \code{\link{spStat}}
#' @family spHelper plots
#'
#' @import ggplot2
#' @import hyperSpec
#'
plot_stat <- function(sp,
                      by =  stop("Argument 'by' is missing."),
                      FUN = stop("Argument 'FUN' is missing."),
                      Title = fCap(as.character(match.call()$FUN)),
					  subTitle = NULL,
                      All = TRUE,
                      fixed.colors = TRUE,
                      All.color = "black",
                      gr.color = c(hyGet.palette(sp),  RColorBrewer::brewer.pal(8,"Dark2")),
                      All.linetype = "dashed",
                      gr.linetype  = "solid",
                      All.size =  1.1,
                      gr.size =  0.8,
                      legend.title = element_blank()
                    )
{
    if (nrow(sp) == 0) {warning("Number of rows in `sp` is 0!"); return(NULL)
    } else {
        varName <- as.character(match.call()$by)
        by <- if (varName %in% colnames(sp)) sp[[,varName]] else by
        # by <- as.factor(by)

        if (All == TRUE) {# All - plot statistic by all spectra?
                sp2 <-    spStat(sp, by = by, FUN = FUN,  Name_of.by = as.character(match.call()$by))
        } else {sp2 <- aggregate(sp, by = by, FUN = FUN)}

        nl.gr  <- sum(levels(sp2$.aggregate) != ".All")

        fixedColors <- if (fixed.colors) {
            colors  <- c(gr.color[1:nl.gr], All.color)
            scale_color_manual(values = colors)
        } else NULL

        p <- qplotspc(sp2, spc.nmax = 10000,
                      mapping = aes(x = .wavelength,
                                    y = spc,
                                    colour   = .aggregate,
                                    group    = .rownames,
                                    size     = .aggregate,
                                    linetype = .aggregate)) +
            labs(title = subt(Title, subTitle)) +
            scale_size_manual(    values = c(rep(gr.size,     nl.gr), All.size))  +
            scale_linetype_manual(values = c(rep(gr.linetype, nl.gr), All.linetype)) + # ,guide=FALSE
            fixedColors +
            theme_bw() +
            theme(legend.title = legend.title)

        return(p)
    }
}


#  ------------------------------------------------------------------------

#' @rdname plot_stat
#' @template same
#' @export
qplotStat <- function(sp, by, FUN = mean, ...) {
    # warning('Use `plot_stat` instead of `qplotStat`')
    plot_stat(sp, by, FUN = FUN, ...)
    }
