#' [!] Plot a summary statistic of spectroscopic data by group.
#'
#' Plot a summary of spectroscopic data in hyperSpec object by group.
#' The summary statistic internally is generated by either function
#' \code{\link{spStat}} or \code{\link[hyperSpec]{aggregate}}
#'
#' @template sp
#' @param by by <- as.factor(by)
#' @param FUN - function of summary statistic to apply.
#' @param Title - ...
#' @param All - plot additional statistic of all spectra
#' @param fixed.colors - flag if color scheme where ".All" is plotted as
#'        a black line shpuld be used.
#' @param All.color - ...
#' @param gr.color - ...
#' @param All.linetype - ...
#' @param gr.linetype - ...
#' @param All.size - ...
#' @param gr.size - ...
#' @param legend.title - ...
#'
#' @seealso \code{\link{spStat}}
#'
#' @template ggplot
#' @export
#'
#' @examples
#'
#'
#' qplotStat(chondro,clusters,mean)
#' qplotStat(chondro,clusters,mean,All=FALSE)
#' qplotStat(chondro,clusters,mean_sd,All=FALSE) + facet_grid(.~clusters)
#'
#' qplotStat(chondro,clusters,median,All=FALSE, fixed.colors=FALSE)
#' qplotStat(chondro,clusters,median, "My Title")
#'
#'
#' # Use .aggregate in make facets, to avoid facet called "NA":
#'
#' qplotStat(chondro,clusters,mean_pm_sd) + facet_grid(.~clusters)
#' qplotStat(chondro,clusters,mean_pm_sd) + facet_grid(.~.aggregate)
#'
qplotStat <- function(sp,
                      by =  stop("Argument 'by' is missing."),
                      FUN = stop("Argument 'FUN' is missing."),
                      Title = fCap(as.character(match.call()$FUN)),
                      All = TRUE,
                      fixed.colors = TRUE,
                      All.color = "black",
                      gr.color = RColorBrewer::brewer.pal(8,"Dark2"),
                      All.linetype = "dashed",
                      gr.linetype  = "solid",
                      All.size =  1.1,
                      gr.size =  0.8,
                      legend.title = element_blank()
)
{
    varName <- as.character(match.call()$by)
    by <- if (varName %in% colnames(sp)) sp[[,varName]] else by
    # by <- as.factor(by)

    # match.call()$by

    if (All == TRUE) {# All - plot statistic by all spectra?
        sp2 <-     spStat(sp, by = by, FUN = FUN)
    } else {sp2 <- aggregate(sp, by = by, FUN = FUN)}


    nl.gr  <- sum(levels(sp2$.aggregate)!=".All")

    fixedColors <- if (fixed.colors){
        colors <- c(gr.color[1:nl.gr], All.color)
        scale_color_manual(values = colors)
    } else NULL


    p <- qplotspc(sp2, spc.nmax = 1000,
                  mapping = aes(x = .wavelength,
                                y = spc,
                                colour   = .aggregate,
                                group    = .rownames,
                                size     = .aggregate,
                                linetype = .aggregate)) +
        labs(title= subt(Title))+
        scale_size_manual(    values=c(rep(gr.size,     nl.gr), All.size))  +
        scale_linetype_manual(values=c(rep(gr.linetype, nl.gr), All.linetype)) + # ,guide=FALSE
        fixedColors +
        theme_bw() +
        theme(legend.title = legend.title)


    return(p)
}
